// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUW_wMG9bMv1oQZZCTQXE4_vfMY9513jc',
    appId: '1:781459256848:web:aed855f321a6d763a4bc95',
    messagingSenderId: '781459256848',
    projectId: 'cathay-hackathon-2023-30761',
    authDomain: 'cathay-hackathon-2023-30761.firebaseapp.com',
    databaseURL: 'https://cathay-hackathon-2023-30761-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cathay-hackathon-2023-30761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASK3E388JWbsiiSe_w1IE20Rzhip960t8',
    appId: '1:781459256848:ios:f22ddb1e0b9e1db0a4bc95',
    messagingSenderId: '781459256848',
    projectId: 'cathay-hackathon-2023-30761',
    databaseURL: 'https://cathay-hackathon-2023-30761-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cathay-hackathon-2023-30761.appspot.com',
    iosBundleId: 'com.example.cathayHackathon2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASK3E388JWbsiiSe_w1IE20Rzhip960t8',
    appId: '1:781459256848:ios:c5a6fa79299953c7a4bc95',
    messagingSenderId: '781459256848',
    projectId: 'cathay-hackathon-2023-30761',
    databaseURL: 'https://cathay-hackathon-2023-30761-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cathay-hackathon-2023-30761.appspot.com',
    iosBundleId: 'com.example.cathayHackathon2023.RunnerTests',
  );
}
